# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

In [18]:
import numpy as np

np.random.seed(1111)

In [19]:
# Create 'starter' matrices
A = np.zeros((2,2))
B = np.zeros((2,2))
C = np.zeros((2,2))

In [20]:
# Create a function to fill with rando ints
def randomatic(A):
    dim = len(A)
    
    for row in range(dim):
        for col in range(dim):
            A[row,col]=np.random.randint(1,10)
    
    return A

In [21]:
A = randomatic(A)
B = randomatic(B)
C = randomatic(C)

print(A)
print(B)
print(C)


[[8. 6.]
 [2. 3.]]
[[5. 9.]
 [7. 5.]]
[[9. 7.]
 [3. 7.]]


## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [27]:
# Your code here
LHS = np.dot(A,(B+C))
RHS = np.dot(A,B) + np.dot(A,C)

print(LHS)
print(RHS)
print(LHS==RHS)

[[172. 200.]
 [ 58.  68.]]
[[172. 200.]
 [ 58.  68.]]
[[ True  True]
 [ True  True]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [28]:
# Your code here
LHS = np.dot(A,np.dot(B,C))
RHS = np.dot(np.dot(A,B),C)

print(LHS)
print(RHS)
print(LHS==RHS)

[[1044. 1288.]
 [ 378.  448.]]
[[1044. 1288.]
 [ 378.  448.]]
[[ True  True]
 [ True  True]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [29]:
# Your code here
LHS = np.dot(A,B)
RHS = np.dot(B,A)

print(LHS)
print(RHS)
print(LHS==RHS)

[[ 82. 102.]
 [ 31.  33.]]
[[58. 57.]
 [66. 57.]]
[[False False]
 [False False]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [5]:
# Your code here 

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 